/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as MapsRouteImport } from "./routes/maps/route";
import { Route as AnalyticsRouteImport } from "./routes/analytics/route";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const MapsRouteRoute = MapsRouteImport.update({
  id: "/maps",
  path: "/maps",
  getParentRoute: () => rootRoute,
} as any);

const AnalyticsRouteRoute = AnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/analytics": {
      id: "/analytics";
      path: "/analytics";
      fullPath: "/analytics";
      preLoaderRoute: typeof AnalyticsRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/maps": {
      id: "/maps";
      path: "/maps";
      fullPath: "/maps";
      preLoaderRoute: typeof MapsRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRouteRoute;
  "/maps": typeof MapsRouteRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRouteRoute;
  "/maps": typeof MapsRouteRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRouteRoute;
  "/maps": typeof MapsRouteRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/analytics" | "/maps";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/analytics" | "/maps";
  id: "__root__" | "/" | "/analytics" | "/maps";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AnalyticsRouteRoute: typeof AnalyticsRouteRoute;
  MapsRouteRoute: typeof MapsRouteRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRouteRoute: AnalyticsRouteRoute,
  MapsRouteRoute: MapsRouteRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analytics",
        "/maps"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analytics": {
      "filePath": "analytics/route.tsx"
    },
    "/maps": {
      "filePath": "maps/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
